# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependency: "
      include: "scope"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "dependency: "
      include: "scope"
    open-pull-requests-limit: 15
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
