name: Django CI

on:
  push:
    branches: ["main", "structure-architecture"]
  pull_request:
    branches: ["main", "structure-architecture"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build docker image
        run: |
          cd backend
          docker compose build
          docker compose up
      - name: Run Tests
        run: |
          cd backend
          docker-compose run tutorai python manage.py test
