name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image and run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          docker compose build
          docker compose run backend python manage.py makemigrations
          docker compose run backend python manage.py migrate
          docker compose up -d
          docker compose run backend python manage.py test
          docker compose down
